### ISSUE TITLE
Add support for tidy runtime on ubuntu 64bits

### ISSUE THREAD

**Issue by carlosflorencio** [c0b41/htmltidy2#5]
Hi,

I am getting this exception on ubuntu 64bits:

```
Uncaught Error: spawn /geartrack/node_modules/htmltidy2/bin/linux/tidy5 ENOENT
      at exports._errnoException (util.js:1034:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
      at onErrorNT (internal/child_process.js:367:16)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

Can you add the 64bits binary?

You would also help these folks:
https://github.com/vavere/htmltidy/issues/11

Thanks

**Comment by c0b41** [comment]
Can you test this? #6

**Comment by carlosflorencio** [comment]
Hi,

Yes, it is working good on windows 64bits & ubuntu 64bits!
But can you add the binaries for linux 32bits aswell? 
I know the 5.4.0 version does not have, but you could add the binary 5.2 linux 32bits just to prevent any errors on these systems.

http://binaries.html-tidy.org/

Thanks!
